# Generated by Django 4.2.6 on 2023-12-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_course_id_remove_episode_id_remove_season_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='uuid',
            new_name='id',
        ),
    ]
