# Generated by Django 4.2.6 on 2023-12-26 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_uuid_course_id_rename_uuid_episode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
